version: 0.0
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Free Trial(d9f5e3d2-298c-4d31-acb2-48fd20533ca3)'
    appType: 'webApp'
    appName: 'test'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

